### ISSUE TITLE
Internal server error when finalized chunked upload content does not match checksum

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/hatrac#11]
If the client specifies a content MD5 checksum for an object version in the upload job, and then the assembled chunks do not match, the job can still be finalized but then subsequent `GET` operations suffer an internal server error due to the integrity check failing. Instead, the finalization should probably fail with a conflict error.

**Comment by karlcz** [comment]
This is now implemented for the POSIX backend in b5730df687b46b54520738e689a7f19d5ef563b3.

**Comment by karlcz** [comment]
@kylechard Do you still work with hatrac at all?  Could you look at implementing this same pre-validation on the S3 backend?  I don't know if the S3 chunked upload finalization will already check the MD5 for us (if so, just make sure the exceptions get mapped appropriately to relay this back to the hatrac client as 409 Conflict) or if it will require finalizing the object in S3, then retrieving it and computing the MD5 again, similar to what I just added in the filesystem backend...

**Comment by kylechard** [comment]
@karlcz I haven't looked at this for a long time. I have a feeling that S3 will not allow the upload to succeed. So it should just be an error mapping. It will take me a little while to get this all set up again, but I'll add it to my list of things to look at.

**Comment by karlcz** [comment]
I'll reassign this to @kylechard and leave it parked in the review column on zenhub rather than closing it, so we can track the remaining bit of S3 work.  I consider the filesystem-backed storage feature to be complete and tested.

**Comment by karlcz** [comment]
Actually, I'm going to close this and tracking the S3 part in a separate issue #21.
