### ISSUE TITLE
Re-creating an object generates an internal server error

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/hatrac#12]
Scenario:
 - create an object
 - delete that object
 - create again that object

You should receive a 409 conflict error.

Instead, in the log file the following exception is printed:

[Fri Feb 12 16:48:58.019167 2016] [:error] [pid 19334] [remote 128.9.128.164:8821] ['Traceback (most recent call last):\\n',
[Fri Feb 12 16:48:58.019188 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/webauthn2/util.py", line 394, in _db_wrapper\\n    val = db_thunk(db)\\n',
[Fri Feb 12 16:48:58.019193 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 491, in db_thunk\\n    result = original_method(*args1, db=db)\\n',
[Fri Feb 12 16:48:58.019197 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 576, in create_name\\n    resource = HatracName.construct(self, **self._create_name(db, name, is_object))\\n',
[Fri Feb 12 16:48:58.019200 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 846, in _create_name\\n    isobject=is_object and 1 or 0\\n',
[Fri Feb 12 16:48:58.019204 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/web/db.py", line 644, in query\\n    self._db_execute(db_cursor, sql_query)\\n',
[Fri Feb 12 16:48:58.019207 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  '  File "/usr/lib/python2.7/site-packages/web/db.py", line 587, in _db_execute\\n    out = cur.execute(query, params)\\n',
[Fri Feb 12 16:48:58.019214 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]  'IntegrityError: duplicate key value violates unique constraint "name_name_key"\\nDETAIL:  Key (name)=(/Microscopy/Scans/test) already exists.\\n\\n']
[Fri Feb 12 16:48:58.019410 2016] [:error] [pid 19334] [remote 128.9.128.164:8821] mod_wsgi (pid=19334): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/hatrac/hatrac.wsgi'.
[Fri Feb 12 16:48:58.019441 2016] [:error] [pid 19334] [remote 128.9.128.164:8821] Traceback (most recent call last):
[Fri Feb 12 16:48:58.019457 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/web/application.py", line 281, in wsgi
[Fri Feb 12 16:48:58.019486 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     result = peep(result)
[Fri Feb 12 16:48:58.019497 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/web/application.py", line 261, in peep
[Fri Feb 12 16:48:58.019514 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     firstchunk = iterator.next()
[Fri Feb 12 16:48:58.019528 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/web/application.py", line 605, in wrap
[Fri Feb 12 16:48:58.019545 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     yield next()
[Fri Feb 12 16:48:58.019555 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/web/application.py", line 597, in next
[Fri Feb 12 16:48:58.019575 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     return result.next()
[Fri Feb 12 16:48:58.019585 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 210, in wrapper
[Fri Feb 12 16:48:58.019601 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     for buf in original_method(*args):
[Fri Feb 12 16:48:58.019629 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/hatrac/rest/name.py", line 116, in PUT
[Fri Feb 12 16:48:58.019653 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     web.ctx.webauthn2_context
[Fri Feb 12 16:48:58.019664 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 495, in wrapper
[Fri Feb 12 16:48:58.019681 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     return args[0]._db_wrapper(db_thunk)
[Fri Feb 12 16:48:58.019693 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]   File "/usr/lib/python2.7/site-packages/webauthn2/util.py", line 458, in _db_wrapper
[Fri Feb 12 16:48:58.019714 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]     raise last_ev
[Fri Feb 12 16:48:58.019730 2016] [:error] [pid 19334] [remote 128.9.128.164:8821] IntegrityError: duplicate key value violates unique constraint "name_name_key"
[Fri Feb 12 16:48:58.019734 2016] [:error] [pid 19334] [remote 128.9.128.164:8821] DETAIL:  Key (name)=(/Microscopy/Scans/test) already exists.
[Fri Feb 12 16:48:58.019737 2016] [:error] [pid 19334] [remote 128.9.128.164:8821]

**Comment by karlcz** [comment]
Does it matter which API you use to create the object (chunked versus whole-file upload)?

**Comment by svoinea** [comment]
Just an empty object:
PUT /hatrac/Microscopy/Scans/test3
DELETE /hatrac/Microscopy/Scans/test3
PUT /hatrac/Microscopy/Scans/test3

**Comment by karlcz** [comment]
Fixed for both whole file and chunked upload, and test case added.

**Comment by svoinea** [comment]
Tested and it works as expected.
