### ISSUE TITLE
Chunked Upload Job Cancellation is not working

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/hatrac#13]
Scenario:
- create an upload job
- cancel the job

Example: 
POST /hatrac/Microscopy/Scans/test7;upload
Result: /hatrac/Microscopy/Scans/test7;upload/6V4HZAACFERIBUAQLOFW5CITXU

DELETE /hatrac/Microscopy/Scans/test7;upload/6V4HZAACFERIBUAQLOFW5CITXU

Result: Error response (404) received: Resource /hatrac/Microscopy/Scans/test7;upload/6V4HZAACFERIBUAQLOFW5CITXU not found.

**Comment by svoinea** [comment]
In the log file, I can see:

[Fri Feb 12 18:39:26.106816 2016] [:error] [pid 23948] [remote 128.9.128.164:208] mod_wsgi (pid=23948): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/hatrac/hatrac.wsgi'.
[Fri Feb 12 18:39:26.106922 2016] [:error] [pid 23948] [remote 128.9.128.164:208] Traceback (most recent call last):
[Fri Feb 12 18:39:26.106966 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/web/application.py", line 281, in wsgi
[Fri Feb 12 18:39:26.107273 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     result = peep(result)
[Fri Feb 12 18:39:26.107295 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/web/application.py", line 261, in peep
[Fri Feb 12 18:39:26.107325 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     firstchunk = iterator.next()
[Fri Feb 12 18:39:26.107353 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/web/application.py", line 605, in wrap
[Fri Feb 12 18:39:26.107391 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     yield next()
[Fri Feb 12 18:39:26.107416 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/web/application.py", line 597, in next
[Fri Feb 12 18:39:26.107461 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     return result.next()
[Fri Feb 12 18:39:26.107501 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 210, in wrapper
[Fri Feb 12 18:39:26.107726 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     for buf in original_method(*args):
[Fri Feb 12 18:39:26.107760 2016] [:error] [pid 23948] [remote 128.9.128.164:208]   File "/usr/lib/python2.7/site-packages/hatrac/rest/transfer.py", line 78, in DELETE
[Fri Feb 12 18:39:26.107892 2016] [:error] [pid 23948] [remote 128.9.128.164:208]     return self.update_response(version)
[Fri Feb 12 18:39:26.107953 2016] [:error] [pid 23948] [remote 128.9.128.164:208] NameError: global name 'version' is not defined

**Comment by karlcz** [comment]
Fixed with new test cases as of e8bbf2ade3ab5364c9dc27e0dc87aab8b686afab.

**Comment by svoinea** [comment]
Tested and works as expected.
