### ISSUE TITLE
DELETE does not work for objects with no current versions

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/hatrac#14]
Example:

GET /hatrac/Microscopy/Scans/test5;versions

returns an empty array ([])

DELETE /hatrac/Microscopy/Scans/test5

returns: 

"Error response (404) received: Resource /hatrac/Microscopy/Scans/test5 currently has no content"

**Comment by karlcz** [comment]
Fixed with new test cases in 0cc8fb1f24d61f7dcfc9a2c5d817c2c7d6a37cb4.

**Comment by svoinea** [comment]
Tested and it works as expected.
