### ISSUE TITLE
Object deletion does not purge its existing upload jobs

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/hatrac#15]
Example:

[root@cirm-devel ~]# ls -l /var/www/hatrac/Microscopy/Scans/
total 0
-rw-r--r--. 1 hatrac apache 0 Feb 12 15:18 test1:FAWMTCWYSBLITMY3RT4XWREO4I

hatrac=> select * from name where id=31;
 id |          name           | subtype | is_deleted |  owner   | create | update | read | subtree-owner | subtree-create | subtree-update | subtree-read 
----+-------------------------+---------+------------+----------+--------+--------+------+---------------+----------------+----------------+--------------
 31 | /Microscopy/Scans/test1 |       1 | t          | {serban} |        |        |      |               |                |                | 
(1 row)

hatrac=> select * from upload;
 id | nameid |            job             |   nbytes   | chunksize |       content_type       |           content_md5            |  owner   
----+--------+----------------------------+------------+-----------+--------------------------+----------------------------------+----------
  2 |     31 | FAWMTCWYSBLITMY3RT4XWREO4I | 1128238016 | 100000000 | application/octet-stream | c1e2704eef8ed246cff33299ec2c600c | {serban}
(1 row)

**Comment by karlcz** [comment]
Fixed with partial test case in c7aa5f3c45d3766b07821e4fd7c7bcfc2b8d4d38. The test exercises the REST API but cannot inspect the db or storage backend for leaks.

To fully review, run a manual test and inspect the storage before and after.

**Comment by svoinea** [comment]
Tested and it works as expected.
In my example, I first undeleted  the test1 object (is_deleted = false).
Then I deleted the test1 object. It purged its existing upload job as well as the file from the hatrac directory.
