### ISSUE TITLE
Recreating a namespace generates a 500 Internal Server Error

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/hatrac#16]
GET /hatrac/Microscopy returns:
[u'/hatrac/Microscopy/Scans', u'/hatrac/Microscopy/20160128-mBN2AApelaTest-SV-0-01-000']

PUT /hatrac/Microscopy returns "500 Internal Server Error".

The trace from the log file:

[Tue Feb 23 17:47:14.536377 2016] [:error] [pid 13715] [remote 128.9.128.164:1385] mod_wsgi (pid=13715): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/hatrac/hatrac.wsgi'.
[Tue Feb 23 17:47:14.536412 2016] [:error] [pid 13715] [remote 128.9.128.164:1385] Traceback (most recent call last):
[Tue Feb 23 17:47:14.536426 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/web/application.py", line 281, in wsgi
[Tue Feb 23 17:47:14.536453 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     result = peep(result)
[Tue Feb 23 17:47:14.536462 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/web/application.py", line 261, in peep
[Tue Feb 23 17:47:14.536479 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     firstchunk = iterator.next()
[Tue Feb 23 17:47:14.536487 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/web/application.py", line 605, in wrap
[Tue Feb 23 17:47:14.536502 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     yield next()
[Tue Feb 23 17:47:14.536510 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/web/application.py", line 597, in next
[Tue Feb 23 17:47:14.536525 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     return result.next()
[Tue Feb 23 17:47:14.536533 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 210, in wrapper
[Tue Feb 23 17:47:14.536548 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     for buf in original_method(*args):
[Tue Feb 23 17:47:14.536556 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]   File "/usr/lib/python2.7/site-packages/hatrac/rest/name.py", line 126, in PUT
[Tue Feb 23 17:47:14.536571 2016] [:error] [pid 13715] [remote 128.9.128.164:1385]     return self.update_response(resource)
[Tue Feb 23 17:47:14.536585 2016] [:error] [pid 13715] [remote 128.9.128.164:1385] TypeError: update_response() takes exactly 1 argument (2 given)

**Comment by karlcz** [comment]
@hongsudt I think this was actually fixed a while ago in edf7cea70cc85997d451e9eae28dd0767f92eaa8 so maybe @svoinea should review it when he's done with stuff for this milestone.

**Comment by svoinea** [comment]
As far as I remember, it was not fixed. My intention was to get a 409 Conflict on an attempt to create namespace that already exists. Instead, I was getting 500 Internal Server Error.
Meanwhile, in my iobox-win32 code, I avoided it by doing first a namespace retrieve, and if NOT FOUND, then create namespace.

**Comment by karlcz** [comment]
OK, I checked and you are right, it was broken.  I have now patched it and added a test case.  I think I'll self-review this and close it.  File a new bug if some other problem with this API is encountered...
