### ISSUE TITLE
ETL script to update existing hatrac to use globus_auth

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/hatrac#17]
We aren't using Hatrac in many real deployments yet.  I think the few that are in use should be reviewed manually and a custom SQL script developed for each one to reflect the desired end state of the Hatrac ACL contents.
- [x] Facebase
- [x] GPCR

Neither of these have meaningful user-level ACL content to preserve, but might globally set a new owner as an appropriate curator group for existing objects.
Both will have a small number of subtree ACLs that permit access at the group level, and these should be reviewed for correctness rather than blindly translating them.

**Comment by karlcz** [comment]
We decided not to change stored ACL formats, so existing databases should work without an ETL for hatrac content.

**Comment by karlcz** [comment]
@ljpearlman  The rewrite is just changing a group name like `g:ff766864-a03f-11e5-b097-22000aef184d` into `https://auth.globus.org/ff766864-a03f-11e5-b097-22000aef184d`, i.e. a sed replacement like `s|^g:|https://auth.globus.org/|` for each old ACL entry, right?

**Comment by karlcz** [comment]
I've added a provisioning script globus_auth_etl.sh in informatics-isi-edu/division@27c23e5f6ab772f9328fd46de4e16ddf69993aa5 that has explicit rules to update the Hatrac ACLs for GPCR and FaceBase.  Can @ljpearlman and @bugacov both review for sanity?  I think it is some self-explanatory SQL.

**Comment by hongsudt** [comment]
@ljpearlman please review.. After that please assign @bugacov to be the next reviewer..

**Comment by ljpearlman** [comment]
This is doing something different than I originally thought it would; instead of translating the existing policies, it's setting specific policies. It looks like that will work (I'm making assumptions about what the ACL structure is liked based on the SQL). I can't speak to whether the policies themselves are the right ones.

**Comment by ljpearlman** [comment]
Actually, I just logged in to a few hosts to poke around, and I have a couple questions:

1. Why aren't subtree-{create,update} being updated?
2. On facebase, why not check for other ACL entries the way they're being checked for on gpcr?

**Comment by karlcz** [comment]
The policy ETL is very specific to the target systems and only modifes the non-empty ACLs that actually do something useful on that system.  Prior to gpcr, our projects were essentially read-only except for a curator here (bugacov) who I've replaced with the isrd-systems group rather than continuing to have a single user listed in ACLs.  The `owner` role subsumes all those possible write scenarios by our systems staff.

**Comment by karlcz** [comment]
@bugacov should review and then close this if it looks ok to him too

**Comment by bugacov** [comment]
Anoop used this script on gpcr-dev so we can close this issue
