### ISSUE TITLE
Content-MD5 header truncated in HEAD response for some values

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/hatrac#18]
Hatrac has object versions with the 32-byte hex `2760ab7799133c03f8e624e3d7939a0d` in the version table's content-md5 field, but a truncated result `Content-MD5: J2Crd5kTPAP45iTj15Oa` appears in the response headers to HEAD.  It should be `Content-MD5: J2Crd5kTPAP45iTj15OaDQ==`.

**Comment by karlcz** [comment]
I think this is fixed in e827b771181cdaa7d774e148545b24cee63ba402

**Comment by hongsudt** [comment]
is this fixed deployed to dev and staging? If so, then I can test.

**Comment by karlcz** [comment]
it is deployed to dev and staging now so you can test.

**Comment by hongsudt** [comment]
The fix works. Will close.
