### ISSUE TITLE
Needs user documentation

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/hatrac#24]
We need at a getting started guide or better yet a user guide with a getting started section. By the end of the section the user should know how to:
- read acls
- modify acls
- create namespaces
- list the objects in a namespace
- create objects
- remove objects
- update objects
- remove namespaces
- etc.

**Comment by karlcz** [comment]
Not sure who you mean by "user"...  that bullet list looks remarkably like the table-of-contents of the REST API docs.  So, I'm not sure what different content you would document.

If you do assume a client programming environment, which one?  CLI with curl?  Browser with Javascript? Or something else...?

A practical barrier at the moment is the webauthn integration.  This is really not an end-user accessible product yet.

**Comment by robes** [comment]
The REST API doc is good for what it is -- an RFC-like specification. But a user guide or getting started section of one, would hand hold a user through some basic interactions with Hatrac, ideally with step by step examples of a small number of representative operations. I would prefer one that simply uses `curl` in examples. It's okay IMO that the webauthn integration depends on an ermrest deployment. Doesn't have to be exhaustive at all, just a few basic commands to get bootstrapped with setting up ACL(s), adding your first file, and getting it afterwards. Doesn't even have to be everything on that list just to get someone going.

**Comment by karlcz** [comment]
See the newly added HOWTO.md in the master branch.

**Comment by robes** [comment]
The commands repeat the `-d username=...` and password. I assume that's just a copy-paste and not needed? Doesn't seem like I need to use them on each call.

**Comment by robes** [comment]
very helpful. thanks
