### ISSUE TITLE
Internal error "ProgrammingError: no results to fetch"

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/hatrac#28]
Request (slightly anonymized): GET /hatrac/target/XYZ_alignment.html

HTTP status: 500

Stack:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web/application.py", line 405, in _delegate
    return handle_class(f)
  File "/usr/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 67, in GET
    return self.METHOD('GET')
  File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 61, in METHOD
    return method(*matchgroups)
  File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 214, in wrapper
    return original_method(*args)
  File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 502, in GET
    return self._GET(*args)
  File "/usr/lib/python2.7/site-packages/hatrac/rest/name.py", line 188, in _GET
    path, name
    result = bodyfunc(self.conn, self.cur)
  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 725, in db_thunk
    return original_method(*args1, conn=conn, cur=cur)
  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1016, in name_resolve
    return HatracName.construct(self, **self._name_lookup(conn, cur, name))
  File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1244, in _name_lookup
    for row in cur:
  File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 91, in __iter__
    first = res.next()
ProgrammingError: no results to fetch
```

**Comment by karlcz** [comment]
This error is pretty strange as it suggests some concurrent or asynchronous use of the DB cursor where the code doesn't seem to do anything wrong at first glance.  I've made an aggressive patch to pre-drain the cursor rather than iterating it, and @bugacov will try to repeat the error conditions.

**Comment by karlcz** [comment]
We have now seen the same `no results to fetch` exception from psycopg2 on the revised code at `for row in list(cur):` so this problem must run deeper...

**Comment by karlcz** [comment]
I think I've finally managed to reproduce this error in a development environment...

**Comment by karlcz** [comment]
I found a severe concurrency bug in the connection-pooling. It seems like the previous code refactoring was incomplete and left things in an inconsistent state, where there was a connection pool but it was used once and a connection held at the singleton directory level!

Commit db8d1ad162fc2278e6f43c6928f2cec37e976d7c fixes this to draw a connection from the pool for each atomic directory operation. This may be overly aggressive but should always work. To access the pool less often, we'd have to split out connection handling to the web worker/thread level and recompose with the directory (or alternatively replace the directory singleton with a per worker/thread directory instance).

The bug manifests itself with concurrent access in multiple threads of the same daemon. You can increase the chances of this in a test environment by changing the wsgi_hatrac.conf to use only one daemon process.  To trigger it, run several instances of the test/rest-smoketest.sh in parallel against the same hatrac service.  Before this new commit, such a test caused failures on almost every run.

**Comment by karlcz** [comment]
@bugacov Please update your test machines and verify that the user-visible problem goes away too.

**Comment by bugacov** [comment]
I still see this error on gpcr production. I just went to 

https://data.gpcrconsortium.org/chaise/record/#1/gpcr_browser:target_gui/title=IMPT-5HT2B

and got the Internal Server Error on the Helix Plot and Snake Plot the first time I tried to access them. After reloading page I was able to see both ok. 
I didn't have the same problem in dev so it maybe that latest fix is still not deployed to production.

**Comment by karlcz** [comment]
Has this hatrac fix been tested in gpcr-www yet?  Can we close this issue?

**Comment by bugacov** [comment]
I just checked on production and I still see those errors.

Anoop, has these hatrac fixes been propagated to production?

Alejandro.

**Comment by karlcz** [comment]
I don't see this in any of the server logs for current gpcr dev, staging, nor www.  Closing.
