### ISSUE TITLE
Internal error "TypeError %d format: a number is required, not NoneType"

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/hatrac#29]
This errors happens randomly in GPCR when trying to access the Helix  and Snake plots under the Target details page. 
Here's the stack trace for a recent error:

Mon Jun 20 16:29:34.375845 2016] [:error] [pid 28200] [remote 128.9.184.181:24] Traceback (most recent call last):
[Mon Jun 20 16:29:34.375889 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
[Mon Jun 20 16:29:34.375893 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return self.handle()
[Mon Jun 20 16:29:34.375896 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
[Mon Jun 20 16:29:34.375899 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return self._delegate(fn, self.fvars, args)
[Mon Jun 20 16:29:34.375902 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/web/application.py", line 405, in _delegate
[Mon Jun 20 16:29:34.375904 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return handle_class(f)
[Mon Jun 20 16:29:34.375906 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
[Mon Jun 20 16:29:34.375909 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return tocall(*args)
[Mon Jun 20 16:29:34.375911 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 67, in GET
[Mon Jun 20 16:29:34.375913 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return self.METHOD('GET')
[Mon Jun 20 16:29:34.375915 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 61, in METHOD
[Mon Jun 20 16:29:34.375917 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return method(*matchgroups)
[Mon Jun 20 16:29:34.375919 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 214, in wrapper
[Mon Jun 20 16:29:34.375921 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return original_method(*args)
[Mon Jun 20 16:29:34.375923 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 502, in GET
[Mon Jun 20 16:29:34.375926 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return self._GET(*args)
[Mon Jun 20 16:29:34.375928 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/rest/name.py", line 191, in _GET
[Mon Jun 20 16:29:34.375930 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     resource = resource.get_current_version()
[Mon Jun 20 16:29:34.375933 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 286, in get_current_version
[Mon Jun 20 16:29:34.375935 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return self.directory.get_current_version(self)
[Mon Jun 20 16:29:34.375943 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 726, in wrapper
[Mon Jun 20 16:29:34.375956 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return args[0].pc.perform(db_thunk, transform)
[Mon Jun 20 16:29:34.375959 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 608, in perform
[Mon Jun 20 16:29:34.375961 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     result = bodyfunc(self.conn, self.cur)
[Mon Jun 20 16:29:34.375963 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 725, in db_thunk
[Mon Jun 20 16:29:34.375966 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     return original_method(*args1, conn=conn, cur=cur)
[Mon Jun 20 16:29:34.375968 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1041, in get_current_version
[Mon Jun 20 16:29:34.375971 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     results = self._version_list(conn, cur, object.id, limit=1)
[Mon Jun 20 16:29:34.375974 2016] [:error] [pid 28200] [remote 128.9.184.181:24]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1279, in _version_list
[Mon Jun 20 16:29:34.375976 2016] [:error] [pid 28200] [remote 128.9.184.181:24]     ("%d" % limit) if limit is not None else 'NULL'
[Mon Jun 20 16:29:34.375978 2016] [:error] [pid 28200] [remote 128.9.184.181:24] TypeError: %d format: a number is required, not NoneType
[Mon Jun 20 16:29:34.375989 2016] [:error] [pid 28200] [remote 128.9.184.181:24] 

and the corresponding line from ssl_access_log:

128.9.184.181 - - [20/Jun/2016:16:29:34 -0700] "GET /hatrac/target/IMPT-5HT1B/IMPT-5HT1B_snake.html HTTP/1.1" 500 21

**Comment by karlcz** [comment]
@bugacov what version of the code (commit ID or tag) is running on this server?

**Comment by bugacov** [comment]
hatrac is at rbk-20160601.1

**Comment by karlcz** [comment]
I have a hard time explaining this bug unless it is related to the other lazy sequencing scenario being investigated in #28 already.  I'm only adding another `assert` statement to check an internal invariant prior to the code that threw the exception in your stack trace.  We'll need to investigate those revised stack traces if you encounter any more errors...

**Comment by bugacov** [comment]
I just got that error again in the staging machine which is under tag  gpcr-20160622.1
(commit ID: face996c07e3103e1c7864bc3533ad74e9c31ccb)

[Thu Jun 23 12:34:04.423235 2016] [:error] [pid 890] [remote 128.9.136.65:160] "in GET /session, referrer arg is 'None', Referrer header is 'https://staging.gpcrconsortium.org
/chaise/record/'"
[Thu Jun 23 12:34:05.513742 2016] [:error] [pid 892] [remote 128.9.136.65:156] Traceback (most recent call last):
[Thu Jun 23 12:34:05.513779 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
[Thu Jun 23 12:34:05.513783 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return self.handle()
[Thu Jun 23 12:34:05.513785 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
[Thu Jun 23 12:34:05.513788 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return self._delegate(fn, self.fvars, args)
[Thu Jun 23 12:34:05.513790 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/web/application.py", line 405, in _delegate
[Thu Jun 23 12:34:05.513793 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return handle_class(f)
[Thu Jun 23 12:34:05.513795 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
[Thu Jun 23 12:34:05.513797 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return tocall(*args)
[Thu Jun 23 12:34:05.513799 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 67, in GET
[Thu Jun 23 12:34:05.513801 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return self.METHOD('GET')
[Thu Jun 23 12:34:05.513803 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/__init__.py", line 61, in METHOD
[Thu Jun 23 12:34:05.513805 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return method(*matchgroups)
[Thu Jun 23 12:34:05.513807 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 214, in wrapper
[Thu Jun 23 12:34:05.513809 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return original_method(*args)
[Thu Jun 23 12:34:05.513811 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 502, in GET
[Thu Jun 23 12:34:05.513813 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return self._GET(*args)
[Thu Jun 23 12:34:05.513815 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/name.py", line 188, in _GET
[Thu Jun 23 12:34:05.513817 2016] [:error] [pid 892] [remote 128.9.136.65:156]     path, name
[Thu Jun 23 12:34:05.513819 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/rest/core.py", line 261, in resolve
[Thu Jun 23 12:34:05.513821 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return web.ctx.hatrac_directory.name_resolve(fullname, raise_notfound)
[Thu Jun 23 12:34:05.513823 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 726, in wrapper
[Thu Jun 23 12:34:05.513825 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return args[0].pc.perform(db_thunk, transform)
[Thu Jun 23 12:34:05.513827 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 608, in perform
[Thu Jun 23 12:34:05.513829 2016] [:error] [pid 892] [remote 128.9.136.65:156]     result = bodyfunc(self.conn, self.cur)
[Thu Jun 23 12:34:05.513831 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 725, in db_thunk
[Thu Jun 23 12:34:05.513843 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return original_method(*args1, conn=conn, cur=cur)
[Thu Jun 23 12:34:05.513846 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1016, in name_resolve
[Thu Jun 23 12:34:05.513848 2016] [:error] [pid 892] [remote 128.9.136.65:156]     return HatracName.construct(self, **self._name_lookup(conn, cur, name))
[Thu Jun 23 12:34:05.513851 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib/python2.7/site-packages/hatrac/model/directory/pgsql.py", line 1245, in _name_lookup
[Thu Jun 23 12:34:05.513853 2016] [:error] [pid 892] [remote 128.9.136.65:156]     for row in list(cur):
[Thu Jun 23 12:34:05.513855 2016] [:error] [pid 892] [remote 128.9.136.65:156]   File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 91, in __iter__
[Thu Jun 23 12:34:05.513857 2016] [:error] [pid 892] [remote 128.9.136.65:156]     first = res.next()
[Thu Jun 23 12:34:05.513859 2016] [:error] [pid 892] [remote 128.9.136.65:156] ProgrammingError: no results to fetch
[Thu Jun 23 12:34:05.513868 2016] [:error] [pid 892] [remote 128.9.136.65:156]

**Comment by karlcz** [comment]
This cannot seem to be reproduced and there are doubts about the server state at time of error...
