### ISSUE TITLE
provide an option to recursively generate the parent namespace if missing

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/hatrac#35]
Add `...?parents=true` query parameter to the URL structure for object, namespace, and upload job creation requests.

**Comment by karlcz** [comment]
@hongsudt  this is implemented in https://github.com/informatics-isi-edu/hatrac/commit/6cf9f50eb1908d57a136e51c3ffc3d69c033034a 

can you please review or assign to someone else for review?

**Comment by hongsudt** [comment]
@chiragsanghvi please verify and close the issue.

**Comment by chiragsanghvi** [comment]
This works.
