### ISSUE TITLE
Return URL to resource in Content-Location header 

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/hatrac#39]
For object HEAD requests that do not specify the object version, return the full URL of the latest version in a Content-Location header.  

Also do this for GET requests, provided it does not cause browsers to do a double-get.  This likely will not happen, but still needs testing.

**Comment by karlcz** [comment]
This is pushed to hatrac master. Please review change and give it a whirl... @mikedarcy

**Comment by mikedarcy** [comment]
Works fine.
