### ISSUE TITLE
Preserve the file name in "save" or "save as" operations on download of versioned resource

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/hatrac#5]
When downloading a file using a web browser, the versioned resource URI will include the version number such as "foo.ext:ver" in the filename. This is inconvenient for the end user as they need to rename the file to strip the ":ver" from the local filename in order to be able to open it by double-clicking or other OS-specific action. It would be preferable to have the browsers "save" or "save as" operation know to save the file without the ":ver" on the suffix. This feature could be optional as part of the deployment configuration.

**Comment by karlcz** [comment]
I've committed a small fix in fe538ff0dcc71548c0fd34bd5ce74e7a74d709dc
