### ISSUE TITLE
Support copy-on-write for dev/testing in aws deployment 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/hatrac#58]
I think the desired way has been discussed, but Mike should comment on status or plans? As I recall, we would want the dev (or staging) hatrac to use a variant of the remote mirror setup, but I don't think the full solution has been baked.

-  You would run some kind of script to initialize its DB with a set of name+version to remote object-version bindings, pointing at the prod hatrac. You might do this periodically to destroy it and resync with prod, similar to how we do dumps and rsync in the colo space to reset the non-prod hatrac.
-  It would also be configured with its own (initially empty) storage space
-  It would apply writes to its local DB and local storage only.  This includes creation of new namespaces, object names, and object versions which would be just like normal hatrac operations in the local state. It would also include deletes or which would just delete the local metadata and "forget" about the remote prod data, but would never pass through any write request back to prod.
- It would lookup reads in its local DB and either serve a local object-version from its own storage or serve the remote prod object-version. I don't think we clearly defined whether it should proxy to the remote hatrac via http or use a (new?) variant of referrals and signed hatrac URLs.

I think there are also security/trust questions around the serving of the shared prod data. Could we get away with the test user having to sign on separately to prod before the access works for these?

Edit: we had a call where we discussed the various worries here. A hybrid approach like this, where the client talks to non-prod and prod at the same time invites interesting and new risks if our testing triggers buggy/bad client behaviors and they ask prod to do something unfortunate. Much hand-wringing left us wondering whether we really want this versus just giving up and making less coherent or less complete test environments, but without so much system coupling. :-/ (edited)

**Comment by karlcz** [comment]
A solution for this exists now in the "overlay" backend type. See its documentation in hatrac/docs/CONFIG.md
