### ISSUE TITLE
Install guide is broken

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/hatrac#6]
Went through the installation guide step by step and it is broken...

1st thing is the configuration probably needs to happen before the running of basic steps.

creating the database should happen by the postgres supersuper because the hatrac user doesn't have createdb permissions.

but even then the tests fail with

psycopg2.ProgrammingError: permission denied for database hatrac_test

I'll keep looking into it, but this install guide seems broken right now.

**Comment by karlcz** [comment]
If you are creating the database via the superuser, be sure to set the
ownership to the hatrac user.  Assuming that works, update the docs. :-)

**Comment by robes** [comment]
I did that: createdb -O hatrac hatrac

And I was working on docs, but I still got stuck on other errors in the smoketest. So until I can (if I can) resolve it, I am not sure its worth committing.

**Comment by karlcz** [comment]
I think this old bug is invalid.  As far as I know, the current instructions work fine as they were also the basis of the travis CI build script and the other provisioning scripts we are using internally.
