### ISSUE TITLE
Using chunked upload job to create object fails with 404 Not Found

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/hatrac#8]
I think that creating a chunked upload job for a new object name should create the empty object (no versions available) implicitly, rather than requiring that the object already exist.

**Comment by karlcz** [comment]
@svoinea please review/test this patch to confirm that objects can be created with the chunked upload (without first creating an empty object of the same name)...

**Comment by svoinea** [comment]
Tested and it works as expected.
